name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend:
    name: Backend lint & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: uv sync --frozen --group dev --group test
        working-directory: backend
      - name: Ruff lint
        run: uv run --group dev ruff check src
        working-directory: backend
      - name: Ruff format check
        run: uv run --group dev ruff format --check src
        working-directory: backend
      - name: Django tests
        run: uv run --group test pytest
        working-directory: backend

  frontend:
    name: Frontend lint & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: frontend
      - name: Lint
        run: npm run lint
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend

  docker:
    name: Build & publish image
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/inventory-app:latest
            ghcr.io/${{ github.repository_owner }}/inventory-app:${{ github.sha }}
